# seed_data.py

users_list = [
    {
        "username": "Demo",
        "email": "demo@aa.io",
        "password": "password",
        "first_name": "demo",
        "last_name": "daDemo",
        "profile_image": "none",
    },
    {
        "username": "marnie",
        "email": "marnie@aa.io",
        "password": "password",
        "first_name": "ma",
        "last_name": "nie",
        "profile_image": "none",
    },
    {
        "username": "bobbie",
        "email": "bobbie@aa.io",
        "password": "password",
        "first_name": "bo",
        "last_name": "bie",
        "profile_image": "none",
    },
    {
        "username": "a",
        "email": "a",
        "password": "a",
        "first_name": "Afirst",
        "last_name": "ALast",
        "profile_image": "none",
    },
]


pin_image_urls = [
    "https://i.ibb.co/2tTmr1B/1.jpg",
    "https://i.ibb.co/mBb3fjc/2.jpg",
    "https://i.ibb.co/0KzTh3p/3.jpg",
    "https://i.ibb.co/DCs8W4p/4.jpg",
    "https://i.ibb.co/4FQ3RfT/5.jpg",
    "https://i.ibb.co/7g5My49/6.jpg",
    "https://i.ibb.co/SyNjSQL/artDeco1.jpg",
    "https://i.ibb.co/jTz15N2/artDeco2.jpg",
    "https://i.ibb.co/Stw2hzj/dragon.jpg",
    "https://i.ibb.co/1Q399Y0/fox.jpg",
    "https://i.ibb.co/0Zx7fnc/freak-Beacon1.jpg",
    "https://i.ibb.co/pXjcV46/gamboy.jpg",
    "https://i.ibb.co/P6GvGLx/images.jpg",
    "https://i.ibb.co/kyY3Hbm/mid-Mid-Desk.jpg",
    "https://i.ibb.co/WvkcHL8/mod-Box-Cabin.jpg",
    "https://i.ibb.co/XXjs0hC/monoRail.jpg",
    "https://i.ibb.co/YWLwNjZ/otter.jpg",
    "https://i.ibb.co/bWwg40q/paint-Waves.jpg",
    "https://i.ibb.co/KGNrg86/sketch.jpg",
    "https://i.ibb.co/N9SQqN0/spider.jpg",
    "https://i.ibb.co/TcdtMQP/spidey.jpg",
    "https://i.ibb.co/2tkqysT/steak.jpg",
    "https://i.ibb.co/nDvGXDh/sunset.jpg",
    "https://i.ibb.co/crsF1fZ/tablet.jpg",
    "https://i.ibb.co/8BFP7RZ/vette.jpg",
]


pin_titles = [
    "Sunset Over the Ocean",
    "Mountain Adventure",
    "City Lights at Night",
    "Serene Lake Views",
    "Autumn Forest Path",
    "Modern Architecture",
    "Abstract Art Piece",
    "Colorful Street Art",
    "Vintage Car Collection",
    "DIY Home Decor Ideas",
    "Minimalist Design",
    "Cozy Reading Nook",
    "Tropical Paradise",
    "Wildlife Photography",
    "Historical Landmarks",
    "Fantasy World",
    "Delicious Recipes",
    "Elegant Fashion",
    "Inspiring Quotes",
    "Fitness Motivation",
    "Gardening Tips",
    "Beautiful Landscapes",
    "Creative Craft Projects",
    "Tech Innovations",
    "Interior Design Trends",
]

pin_descriptions = [
    "Experience the tranquility of a sunset over the ocean with this stunning visual representation. The colors and composition capture the peaceful essence perfectly.",
    "Join in on a thrilling mountain adventure. This pin highlights the beauty and excitement of exploring the great outdoors, from breathtaking peaks to lush valleys.",
    "Explore the vibrant city lights at night. This pin captures the energy and beauty of urban landscapes under the glow of city lights, showcasing a different side of the city.",
    "Discover serene lake views with this pin. The calm waters and surrounding nature create a peaceful and relaxing atmosphere, perfect for unwinding and enjoying the beauty of nature.",
    "Take a walk down an autumn forest path. The rich colors of the fall foliage and the crisp air make this a perfect escape into nature's seasonal beauty.",
    "Marvel at the creativity of modern architecture. This pin showcases innovative designs and structures that push the boundaries of traditional building aesthetics.",
    "Dive into the world of abstract art with this unique piece. The bold colors and dynamic shapes invite viewers to interpret and connect with the artwork in their own way.",
    "Explore the vibrant and colorful world of street art. This pin features eye-catching murals and graffiti that bring life and creativity to urban environments.",
    "Admire a collection of vintage cars. This pin showcases classic vehicles, highlighting their timeless design and the nostalgia they evoke.",
    "Get inspired with DIY home decor ideas. This pin offers creative and budget-friendly projects to personalize and enhance your living space.",
    "Embrace the beauty of minimalist design. This pin highlights clean lines, simple forms, and a focus on functionality that define the minimalist aesthetic.",
    "Create a cozy reading nook in your home. This pin provides ideas for designing a comfortable and inviting space perfect for curling up with a good book.",
    "Escape to a tropical paradise with this pin. The lush greenery, clear blue waters, and sandy beaches evoke the ultimate relaxation and getaway experience.",
    "Capture the beauty of wildlife with this pin. Stunning photography showcases animals in their natural habitats, highlighting the diversity and wonder of the animal kingdom.",
    "Visit historical landmarks around the world. This pin features iconic sites that hold cultural and historical significance, offering a glimpse into the past.",
    "Enter a fantasy world with this pin. Imaginative and creative, this pin transports viewers to a realm of magic and adventure, filled with mythical creatures and epic landscapes.",
    "Discover delicious recipes to try at home. This pin offers a variety of dishes, from appetizers to desserts, that are sure to impress and satisfy your taste buds.",
    "Stay stylish with elegant fashion inspiration. This pin features chic and timeless outfits that are perfect for any occasion, from casual to formal.",
    "Find motivation with inspiring quotes. This pin features uplifting and thought-provoking quotes that encourage positive thinking and personal growth.",
    "Boost your fitness motivation with this pin. Featuring workout routines, tips, and success stories, this pin is perfect for anyone looking to improve their health and fitness.",
    "Enhance your gardening skills with expert tips. This pin provides valuable advice on planting, maintenance, and design to help you create a beautiful and thriving garden.",
    "Explore beautiful landscapes from around the world. This pin features breathtaking scenery, from mountains and forests to deserts and coastlines.",
    "Get creative with craft projects. This pin offers a variety of DIY ideas and tutorials for making unique and personalized items, perfect for crafters of all skill levels.",
    "Stay up-to-date with tech innovations. This pin highlights the latest advancements and trends in technology, showcasing cutting-edge gadgets and solutions.",
    "Transform your space with the latest interior design trends. This pin features stylish and innovative ideas for updating and decorating your home.",
]


comments = [
    "This is amazing!",
    "Love the colors in this one.",
    "Absolutely stunning.",
    "Great composition!",
    "Very inspiring work.",
    "Such a unique style!",
    "This made my day!",
    "Incredible detail.",
    "I can't stop looking at this.",
    "Simply beautiful.",
    "How did you create this?",
    "Wow, just wow.",
    "This is a masterpiece.",
    "Breathtaking view!",
    "Excellent work!",
    "Fantastic creativity.",
    "So much talent here.",
    "I wish I could do this.",
    "Really impressive!",
    "Keep up the great work!",
    "This is so cool!",
    "Totally love this.",
    "A true work of art.",
    "Wonderful execution!",
    "Bravo!",
]
